FROM openjdk:11-jdk-slim

WORKDIR /app

COPY pom.xml ./
COPY src ./src

EXPOSE 8080 5005

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
