services:
  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: movies_dev
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  redis:
    image: redis:7
    container_name: redis-container
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    container_name: minio-container
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio/data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: app-container
    ports:
      - "8080:8080"
      - "5005:5005"
    environment:
      SPRING_PROFILES_ACTIVE: dev
      URL_DATASOURCE: jdbc:postgresql://postgres:5432/movies_dev
      USERNAME: postgres
      PASSWORD: admin
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MINIO_URL: http://minio:9000
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
      MINIO_BUCKET_NAME: movies
    depends_on:
      - postgres
      - minio
      - redis
    volumes:
      - .:/app
      - ~/.m2:/root/.m2